/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni.JniTest */

#ifndef _Included_JniTest
#define _Included_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni.JniTest
 * Method:    definePrinte
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jni_JniTest_definePrint
        (JNIEnv *, jobject, jstring);


JNIEXPORT jstring JNICALL Java_jni_JniTest_getStringFromJni(JNIEnv *env, jobject thiz);

JNIEXPORT void JNICALL
Java_jni_JniTest_showToastFromCOrCPlusPlus(JNIEnv *env, jobject thiz, jobject context,
                                           jstring toast_content);

JNIEXPORT void JNICALL
Java_jni_JniTest_jniRef(JNIEnv *env, jobject thiz);

#ifdef __cplusplus
}
#endif
#endif
